### ISSUE TITLE
Minor issue with if statement

### ISSUE THREAD

**Issue by pavdmyt** [akittas/presentations#2]
In **meta_alltheway.ipynb** inside *'Our example with a function as metaclass'* there is a following block:

```python
for attr_name, attr_val in attrs.items():
    if not name.startswith('__'):
        snake_attrs[convert(attr_name)] = attr_val
    else:
        snake_attrs[attr_name] = attr_val
```

I suppose it should be `if not attr_name.startswith('__')` as method names should be checked, not the class name.

The same issue with *'Our example with a class as metaclass'* example.

Anyway, thanks a lot! It's a great material.

**Comment by akittas** [comment]
Thanks a lot for noting that, it is fixed now.
